{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: "dcgm-exporter"
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    app.kubernetes.io/name: "dcgm-exporter"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "dcgm-exporter"
  namespaceSelector:
    matchNames:
      - {{ .Values.namespace }}
  endpoints:
    - port: "metrics"
      path: "/metrics"
      interval: {{ .Values.serviceMonitor.interval }}
{{- end -}}